services:
  - type: private_service 
    name: dominoz-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python renderdemo/main.py"
    envVars:
      - key: SERVER_NAME
        value: "OfficialDominoz"
      - key: MAX_PLAYERS
        value: "6"
      - key: MAX_LOBBIES
        value: "16"
      - key: DIFFICULTY
        value: "normal"
      - key: PORT
        value: "5555"
      - key: HOST
        value: "0.0.0.0"
